name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install

    - name: Build
      run: cmake --build ${{github.workspace}}/build -- -j 8 

    - name: Install 
      run: cmake --install build

  build_debug:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build ${{github.workspace}}/build -- -j 8 

    - name: Install 
      run: cmake --install build

    - name: Unit tests
      run: ctest --test-dir ${{github.workspace}}/build/test --output-on-failure
